import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/HomeBanner'
import ThePs from '../components/The4ps'
import Naut from '../components/Nautilius'
import Servcies from '../components/OurServices'
import Contact from '../components/Contactus'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ship Management Company, Vessel Management Services | Nautilus Shipping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
    
<Header/>
<Banner/>
<ThePs/>
<Naut/>
<Servcies/>
<Contact/>
<Footer/>
    </>
  )
}
